In [41]:
import pandas as pd
import numpy as np

In [60]:
raw = pd.read_csv('data/training.csv',index_col=0)

In [55]:
final = pd.read_csv('cosine_similarity', index_col=0)

In [61]:
raw.head()

,question1,question2,is_duplicate
id,,,
667,What is fermentation? What are some products o...,What are some fermented products?,0
178769,What are the effects of the divided government...,What are the effects of the divided government...,0
365554,Do employees at McDonald's have a good work-li...,Do employees at Walmart have a good work-life ...,0
56745,What is it like to be newly wed?,What do newly weds do on their honeymoon?,0
15608,How do I delete old gmail accounts?,How do I know if my WhatsApp account has been ...,0

In [57]:
final.head()

,question1,question2,q1_vector,q2_vector,output
id,,,,,
124132,How did people benefit from the Agricultural R...,"If teleportation was somehow possible, how wou...","[0.05645574185836787, 0.01229167527213138]","[0.05668638658419941, -0.021492952948728362]",0.838220
372338,How many times a normal girl can have sex in a...,What is wrong with me? Sometimes I wake up wit...,"[0.07179628526603758, 0.008452525873686974]","[-0.019597324869145245, -0.014801990764510886]",-0.862959
39767,What are your favorite YA novels?,Question about music in college?,"[-0.03215328069256384, 0.05470470981843766]","[0.020093474653235213, -0.006977727850326362]",-0.761488
99057,How frequently can I have chicken livers safely?,Is it safe for dogs to eat chicken? Why or why...,"[0.08110567893426847, 0.007912608062867272]","[0.089450792886284, -0.06184429225633101]",0.763444
67751,How should I live happily at home?,How do I live happily with no friends?,"[0.06522090108107786, -0.01473527230563844]","[0.10309020384659172, -0.006104187502300721]",0.986736

In [63]:
final.loc[39767]

question1                What are your favorite YA novels?
question2                 Question about music in college?
q1_vector      [-0.03215328069256384, 0.05470470981843766]
q2_vector    [0.020093474653235213, -0.006977727850326362]
output                                           -0.761488
Name: 39767, dtype: object

In [62]:
raw.loc[39767]

question1       What are your favorite YA novels?
question2        Question about music in college?
is_duplicate                                    0
Name: 39767, dtype: object

In [72]:
df = raw.join(final['output'], how = 'inner', on = raw.index).drop(columns ='key_0')

In [73]:
df.sort_values(by = ['output'])

,question1,question2,is_duplicate,output
id,,,,
307121,Sleep: How do you figure out your ideal amount...,What is the ideal amount of time to sleep?,1,-0.986677
371005,How much is a software engineer paid per month...,How much are software engineers paid for worki...,1,-0.976367
235080,At what rate does mass increase for an object ...,Why does mass increase with velocity as an obj...,0,-0.974029
295810,I think going off meds (reduced) made me outsi...,What meds have the best results for your bipol...,0,-0.966861
103590,What are the best sources to learn digital mar...,How can I learn digital marketing?,1,-0.958455
...,...,...,...,...
297637,Plz any body is from lasi Romania I really nee...,"Anybody is from lasi, romania plz I really nee...",1,0.999859
374541,What is the expected cutoff for KVPY SX Aptitu...,What is the expected cutoff for KVPY SX 2016?,1,0.999903
96716,Can I make unlimited international voice calls...,How do you fix an iPhone that has a white scre...,0,0.999998
386375,Do men expect too much from women?,Do women expect too much from men?,0,1.000000
256553,Can someone add u on WhatsApp if I have a difr...,Can someone add u on WhatsApp if I have a dife...,1,1.000000